"""empty message

Revision ID: 1f8b001819f8
Revises: ae5199da6aae
Create Date: 2023-10-06 10:46:02.255910

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1f8b001819f8'
down_revision = 'ae5199da6aae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pregnancy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_fullname', sa.String(length=150), nullable=False))
        batch_op.drop_constraint('pregnancy_ibfk_1', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pregnancy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('pregnancy_ibfk_1', 'patient', ['user_id'], ['user_id'])
        batch_op.drop_column('user_fullname')

    # ### end Alembic commands ###
