"""empty message

Revision ID: 54b818b6ad22
Revises: 0c815b5117c8
Create Date: 2023-10-09 01:46:45.226015

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '54b818b6ad22'
down_revision = '0c815b5117c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pregnancy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pat_id', sa.Integer(), nullable=True))
        batch_op.alter_column('edd',
               existing_type=mysql.DATETIME(),
               type_=sa.Date(),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'patient', ['pat_id'], ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pregnancy', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('edd',
               existing_type=sa.Date(),
               type_=mysql.DATETIME(),
               existing_nullable=True)
        batch_op.drop_column('pat_id')

    # ### end Alembic commands ###
