"""empty message

Revision ID: a38247a6b21d
Revises: 
Create Date: 2023-10-01 17:52:33.073221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a38247a6b21d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_ailments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('advice', sa.String(length=450), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_ailments', schema=None) as batch_op:
        batch_op.drop_column('advice')

    # ### end Alembic commands ###
