"""empty message

Revision ID: bd17c830492e
Revises: 4e63d3abdbf4
Create Date: 2023-10-03 08:43:29.313416

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bd17c830492e'
down_revision = '4e63d3abdbf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_ailments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('diagnosis_date', sa.Date(), nullable=True))
        batch_op.alter_column('advice',
               existing_type=mysql.VARCHAR(length=450),
               type_=sa.String(length=500),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_ailments', schema=None) as batch_op:
        batch_op.alter_column('advice',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(length=450),
               existing_nullable=False)
        batch_op.drop_column('diagnosis_date')

    # ### end Alembic commands ###
